### ISSUE TITLE
[Vue warn]: Error when rendering component <my-head>

### ISSUE THREAD

**Issue by xu-snow** [jide123456/blog#1]
`npm run dev` 后在跳到 /article/:id ,也就是运行article.vue 时出现bug，页面打开报错：

     [Vue warn]: Error when rendering component <my-head> at
     TypeError: Cannot read property 'ctn' of undefined

我看你的博客上也报了这个错误，但是页面能打开，但是到我这就不行了，可能是vue版本或其它原因
debug之后发现是因为在
**head.vue** 

    bg = this.article && this.article.bg.ctn

取不到article.bg.ctn 这个二级属性，换成其它的一级属性article.data,article.title都是可以的。包括上面的article.classes.name也是因为取不到所以页面报错。
尝试一番之后，我在 article.vue 中修改下面的代码

	data () {
		return {
			article: {}
		}
	},

修改成这样

	data () {
		return {
			article: {classes:{},bg:{}}
		}
	},

页面正常

不知道还有其它做法没有？

**Comment by jide123456** [comment]
@xu-snow  不好意思，现在才看到你提的issue

你说的这个问题我也发现了，应该就是二级属性取不到所导致的。 我的处理方式同你一样。

在现版本（v2.0）的head组件设计中，我取消了article[Object]的props，改成了3个字符串的props，分别是titile，bgUrl，description，对应的判断背景图前缀的逻辑我也抽出放到了调用页，这样复用性和可读性会更好点。
