### ISSUE TITLE
npm run dev 时报错

### ISSUE THREAD

**Issue by Cheese-Yu** [jide123456/blog#2]
http://localhost:3000/resource/category/ 404 (Not Found)
不知是什么原因，请问该如何解决？如果部署到服务器上，该如何操作？小白，求指教~

**Comment by Cheese-Yu** [comment]
报错是因为我没有运行后端代码。但是本地测试没有后端登录页面，请问如何开启呢？添加分类时，提示错误：Cannot read property 'last' of null。。。该如何解决？额，我的问题有点多。。

**Comment by jide123456** [comment]
@Cheese-Yu   你好，看见的有点完。 不知道你的问题解决了没有。
关于部署， 首页你得在服务器上安装node， 然后将后端代码上传至服务器，安装依赖包， 再在前端代码里执行 npm run build， 把构建好的代码上传至服务器， 然后应该就能访问了。 如果有不懂得可以细问。

第二个问题， 我去看了下添加分类的逻辑，没有发现哪个方法里用了last属性，你可以提供更详细的报错信息。
